[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yeetcode"
version = "0.0.1"
authors = [
  { name="Qianxy", email="xyqian67@gmail.com" },
]
description = "Leetcode skeletal clone"
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/qianxyz/yeetcode"
